# Generated by Django 5.0 on 2023-12-10 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.huesped')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.tipopago')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
