# Generated by Django 5.0 on 2023-12-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_remove_reserva_total_pagar_reserva_tipo_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='huesped',
            field=models.CharField(max_length=255, verbose_name='Nombre del huésped'),
        ),
    ]
