# Generated by Django 5.0 on 2023-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_alter_reserva_huesped'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
